CREATE TABLE people (
	id SERIAL PRIMARY KEY,
	name varchar(64) NOT NULL,
	full_name varchar(128)
);

CREATE TABLE users (
	person INTEGER PRIMARY KEY REFERENCES people(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	password VARCHAR
);

CREATE TABLE companies (
	id SERIAL PRIMARY KEY,
	name VARCHAR(64) NOT NULL
);

CREATE TABLE employees (
	person INTEGER NOT NULL REFERENCES people(id) ON UPDATE CASCADE ON DELETE CASCADE,
	company INTEGER NOT NULL REFERENCES companies(id) ON UPDATE CASCADE ON DELETE CASCADE,
	position VARCHAR(48),
	PRIMARY KEY(person, company)
);

CREATE TABLE projects (
	id SERIAL PRIMARY KEY,
	title VARCHAR(64) NOT NULL,
	parent INTEGER REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
	description TEXT
);

CREATE TABLE project_members (
	person INTEGER NOT NULL REFERENCES people(id) ON UPDATE CASCADE ON DELETE CASCADE,
	project INTEGER NOT NULL REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
	role VARCHAR(48),
	PRIMARY KEY(person, project)
);

CREATE TABLE tasks (
	id SERIAL PRIMARY KEY,
	title VARCHAR(128) NOT NULL,
	owner INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE RESTRICT,
	assignee INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE CASCADE,
	project INTEGER REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
	start_date DATE NOT NULL DEFAULT NOW(),
	estimated_time FLOAT DEFAULT 0,
	priority INTEGER NOT NULL,
	time_created TIMESTAMP NOT NULL DEFAULT NOW(),
	time_completed TIMESTAMP DEFAULT NULL,
	description TEXT
);

CREATE TABLE task_comments (
	id SERIAL PRIMARY KEY,
	task INTEGER NOT NULL REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE,
	owner INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE RESTRICT,
	time_created TIMESTAMP NOT NULL DEFAULT NOW(),
	content TEXT
);

CREATE TABLE task_time_records (
	task INTEGER NOT NULL REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE,
	assignee INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE CASCADE,
	time_entered TIMESTAMP NOT NULL DEFAULT NOW(),
	required_time FLOAT DEFAULT 0,
	PRIMARY KEY (task, assignee)
);
