CREATE TABLE people (
	id SERIAL PRIMARY KEY,
	name varchar(64) NOT NULL,
	full_name varchar(128)
);

CREATE TABLE users (
	person INTEGER PRIMARY KEY REFERENCES people(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	password VARCHAR
);


CREATE TABLE tasks (
	id SERIAL PRIMARY KEY,
	title VARCHAR NOT NULL,
	owner INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE RESTRICT,
	assignee INTEGER NOT NULL REFERENCES users(person) ON UPDATE CASCADE ON DELETE RESTRICT,
	creation_date DATE NOT NULL DEFAULT NOW(),
	start_date DATE,
	description TEXT
);
